os-fpga/rapid_power_estimator

backend/submodule/clock.py

Implement partial clock power computation

Implement partial clock power computation

---

backend/device/device_xml_parser.py
backend/restapi_server.py
backend/submodule/clock.py
backend/submodule/rs_device.py
backend/utilities/common_utils.py

This PR implemented the clocking power calculation that takes into consideration of clock signal fanout to the FLE module.

Implement clocking power calculation

---

backend/schema/device_fabric_logic_element_schemas.py
backend/submodule/clock.py
backend/submodule/device_manager.py
backend/submodule/fabric_logic_element.py
backend/submodule/rs_device.py

This PR implemented the power calculation for FLE.

Implement power calculation for FLE

---

backend/restapi_server.py
backend/schema/device_dsp_schemas.py
backend/submodule/device_manager.py
backend/submodule/dsp.py
backend/submodule/rs_device.py

This PR implemented the DSP module (without power calculation) and REST endpoints for CRUD operations.

Implement DSP module and REST endpoints for CRUD operation

---

backend/restapi_server.py
backend/schema/device_bram_schemas.py
backend/submodule/bram.py
backend/submodule/device_manager.py
backend/submodule/rs_device.py

This PR implemented the BRAM rest endpoint and basic crud operations without power consumption calculation.

Implement BRAM rest endpoint and basic crud operations

---

backend/restapi_server.py
backend/schema/device_io_schemas.py
backend/submodule/bram.py
backend/submodule/clock.py
backend/submodule/device_manager.py
backend/submodule/dsp.py
backend/submodule/fabric_logic_element.py
backend/submodule/io.py
backend/submodule/rs_device.py
backend/submodule/rs_device_manager.py
backend/submodule/rs_device_resources.py
src/assets/dsp.js

This PR added the IO REST endpoints and the basic CRUD operations. And also, it refactored the code to generalize CRUD operations in device manager class.

Implement IO REST endpoints

---

backend/restapi_server.py
backend/schema/device_io_schemas.py
backend/submodule/io.py

This PR implemented the IO resource utilization structures and power consumption output json structure returned by the API endpoint.

Implement IO resource utilization structures and power consumption return result

---

src/App.js
src/assets/bram.js
src/assets/common.js
src/assets/serverAPI.js
src/components/BramModal.js
src/components/BramTable.js
src/components/ClockingModal.js
src/components/ClockingTable.js
src/components/DspModal.js
src/components/DspTable.js
src/components/FleModal.js
src/components/FleTable.js
src/components/FpgaTable.js
src/components/ModalWindow.js
src/components/PowerTable.js

* Convert rate values to percents
* Make more structure Port A/B fields

Add BRAM table

---

src/components/Tables/BramTable.js
src/components/Tables/ClockingTable.js
src/components/Tables/DspTable.js
src/components/Tables/FleTable.js
src/components/Tables/IOTable.js
src/components/Tables/TableBase.js

Add two new components: 
* Actions - represents action column with Edit/Delete buttons
* TableBase - table component, which takes header and data as props and build table.

GUI: Improve structure for the tables

---

src/App.js
src/components/CPUComponent.js
src/components/Peripherals.js
src/components/Tables/BramTable.js
src/components/Tables/DspTable.js
src/components/Tables/FleTable.js
src/components/Tables/PeripheralsTable.js
src/components/Tables/TableBase.js
src/components/style/Peripherals.css
src/utils/common.js
src/utils/peripherals.js
src/utils/serverAPI.js

Add basic Peripherals table

---

backend/submodule/bram.py
backend/submodule/clock.py
backend/submodule/dsp.py
backend/submodule/fabric_logic_element.py
backend/submodule/io.py
backend/submodule/rs_device.py
backend/utilities/common_utils.py

This PR implemented the Processor (BCPU & ACPU) & the Fabric complex endpoints. Besides, the PR fixed below issues:-
1. Fixed BRAM power calculation error
2. Removed redundant code
3. Minor rework for comment leftover from previous 'Implement DSP power calculation' PR

Implement Processor and Fabric complex endpoints

---

backend/restapi_server.py
backend/schema/device_peripheral_schemas.py
backend/submodule/peripherals.py

This PR implemented the FPGA Complex REST API endpoints and data class model.

implement FPGA Complex REST API endpoint and data class model

---

src/App.js
src/components/CPUComponent.js
src/components/MemoryComponent.js
src/components/ModalWindows/MemoryModal.js
src/components/PeripheralsComponent.js
src/components/SOCComponent.js
src/components/Tables/MemoryTable.js
src/components/Tables/PeripheralsTable.js
src/components/Tables/SOCTable.js
src/components/Tables/TableBase.js
src/components/style/DeviceList.css
src/components/style/FpgaComponent.css
src/components/style/MemoryComponent.css
src/components/style/SOCTable.css
src/components/style/TitleComponent.css
src/style.css
src/utils/peripherals.js

Add Memory table

---

src/components/ModalWindows/ABCPUModal.js
src/components/ModalWindows/ConnectivityModal.js
src/components/ModalWindows/PeripheralsModal.js
src/components/Tables/ACPUTable.js
src/components/Tables/BCPUTable.js
src/components/Tables/ConnectivityTable.js
src/components/Tables/PeripheralsTable.js
src/utils/cpu.js
src/utils/peripherals.js

Updates:
* Rework ACPUTable, BCPUTable, PeripheralsTable, ConnectivityTable
* Make code more readable and simple
* Improve performance
* Set user value step for Toggle Rate to 0.5
Note. No visible changes.

Rework few tables to make it more simple and improve performance

---

.github/workflows/rpe_test.yml

Along with tag, also trigger on branch push

Update rpe_test.yml to trigger on any branch push

---

package.json
src/App.js
src/components/FPGASummaryComponent.js
src/components/ModalWindows/ModalWindow.js
src/components/Notes.js
src/components/SOCSummaryComponent.js
src/components/Tables/ACPUTable.js
src/components/Tables/PowerSummaryTable.js
src/components/Tables/TableCells.js
src/components/TypicalWorstComponent.js
src/components/style/Modal.css
src/components/style/PowerSummaryTable.css
src/components/style/PowerTable.css
src/components/style/TypicalWorstComponent.css
src/style.css
src/utils/common.js

Update:
* Add FPGA Complex and Core Power
* Add Processing Complex (SOC) Power
* Add switch controls
* Add Typical/Worst table
* Add Note window

Add power summary tables and other controls

---

src/App.js
src/components/Tables/ACPUTable.js
src/components/Tables/BCPUTable.js
src/components/Tables/BramTable.js
src/components/Tables/ClockingTable.js
src/components/Tables/ConnectivityTable.js
src/components/Tables/DMATable.js
src/components/Tables/DesignParametesTable.js
src/components/Tables/DspTable.js
src/components/Tables/FleTable.js
src/components/Tables/IOPowerTable.js
src/components/Tables/IOTable.js
src/components/Tables/MemoryTable.js
src/components/Tables/PeripheralsTable.js
src/components/Tables/PowerSummaryTable.js
src/components/Tables/PowerTable.js
src/components/Tables/TableBase.js
src/components/TypicalWorstComponent.js
src/components/style/ACPUTable.css
src/components/style/ComponentTable.css
src/components/style/DesignParametesTable.css
src/components/style/DeviceList.css
src/components/style/PowerSummaryTable.css
src/components/style/PowerTable.css
src/components/style/TypicalWorstComponent.css
src/style.css

Add one style for all borders.

Update border style for all elements

---

backend/restapi_server.py
backend/schema/device_schemas.py
backend/submodule/peripherals.py
backend/submodule/rs_device.py

This PR added the endpoint that returns total thermal and power consumption of a device.

Device total power and thermal endpoint

---

.eslintrc.json
.github/workflows/rpe_test.yml
babel.config.js
jest.config.js
package.json
src/components/DeviceList.js
src/tests/App.test.js
src/tests/DeviceList.test.js
src/tests/FpgaCell.test.js

Enable unit tests for the frontend
How it looks like when tests failed:

Enable unit tests for the frontend

---

backend/schema/device_bram_schemas.py
backend/schema/device_clocking_schemas.py
backend/schema/device_dsp_schemas.py
backend/schema/device_fabric_logic_element_schemas.py
backend/schema/device_io_schemas.py
backend/schema/device_peripheral_schemas.py
backend/schema/device_schemas.py
backend/submodule/bram.py
backend/submodule/clock.py
backend/submodule/dsp.py
backend/submodule/fabric_logic_element.py
backend/submodule/io.py
backend/submodule/peripherals.py
backend/submodule/rs_device.py
backend/submodule/rs_device_resources.py
backend/submodule/rs_message.py
tests/test_clock.py

This PR updated to all submodules (DSP, Clock, LE, IO, Peripheral, BRAM) to return array of messages and their types (error, warn & info) to indicate status of the items of the submodules.

Update endpoint to array of messages and types

---

.github/workflows/rpe_test.yml

Execute Front end test on CentOS 7

Run Frontend test on CentOS 7 as well

---

package.json

Added repository GitHub URL in package,json so that packaging tool can point to it.

Update package.json to add repo info

---

.github/workflows/Dockerfile
.github/workflows/rpe_test.yml
package.json

Fix the permission issues related to the release upload
Append "linux" to the package Linux
Turn off auto publishing of electron builder to control it manually

Fix issue for uploading installer to GH release via GH actions

---

src/App.js
src/ClockSelectionProvider.js
src/components/ABCPUComponent.js
src/components/ComponentsLib.js
src/components/ModalWindows/BramModal.js
src/components/ModalWindows/ClockingModal.js
src/components/ModalWindows/ConnectivityModal.js
src/components/ModalWindows/DspModal.js
src/components/ModalWindows/FleModal.js
src/components/ModalWindows/IOModal.js
src/components/ModalWindows/ModalWindow.js
src/components/PeripheralsComponent.js
src/components/Tables/ACPUTable.js
src/components/Tables/BCPUTable.js
src/components/Tables/BramTable.js
src/components/Tables/ClockingTable.js
src/components/Tables/ConnectivityTable.js
src/components/Tables/DesignParametesTable.js
src/components/Tables/DspTable.js
src/components/Tables/FleTable.js
src/components/Tables/IOTable.js
src/components/style/DesignParametesTable.css
src/components/style/Peripherals.css
src/index.js
src/utils/common.js
src/utils/designParameter.js

Change list:
* Update Design parameters table
* Rework clock field for all tables from text field to dropdown list
* Add new component - Dropdown, which replaces <select> tag with high level component.

Design parameters update

---

src/components/Tables/ACPUTable.js
src/components/Tables/BCPUTable.js
src/components/Tables/BramTable.js
src/components/Tables/ClockingTable.js
src/components/Tables/ConnectivityTable.js
src/components/Tables/DMATable.js
src/components/Tables/DspTable.js
src/components/Tables/FleTable.js
src/components/Tables/IOTable.js
src/components/Tables/MemoryTable.js
src/components/Tables/PeripheralsTable.js
src/components/Tables/TableBase.js
src/components/style/ComponentTable.css
src/components/style/ComponentsLib.css

Change list:
* Remove unnecessary React useEffect hooks to improve performance
* Add status column for all tables. This will reflect status and message of each table row.
* Make fixed columns for status, actions and enable/disable state. 
Note. Message appears after mouse hover over the status icon. For row is not implemented yet because it is some complexity with implementation. This is for further discussion.

Improve performance for all components tables, add status column

---

src/components/FpgaCell.js
src/components/style/FpgaComponent.css
src/components/style/Peripherals.css
src/components/style/SOCTable.css

Fixed height issue with main table

Fixed height issue with main table

---

src/App.js
src/SOCTotalPowerProvider.js
src/components/CPUComponent.js
src/components/ConnectivityComponent.js
src/components/DMAComponent.js
src/components/FPGASummaryComponent.js
src/components/FpgaComponent.js
src/components/MemoryComponent.js
src/components/PeripheralsComponent.js
src/components/SOCComponent.js
src/components/SOCSummaryComponent.js
src/components/Tables/BramTable.js
src/components/Tables/ClockingTable.js
src/components/Tables/DspTable.js
src/components/Tables/FleTable.js
src/components/Tables/IOTable.js
src/components/Tables/PowerSummaryTable.js
src/components/TitleComponent.js
src/components/TypicalWorstComponent.js
src/utils/common.js

Change list:
* Update UI for using new consumption API
* All total power collected in one place
* All done via context object
* All components tables trigger updating total power

Fixed UI for new consumption API

---

main.js
package.json
preload.js
projectFile.js
src/App.js
src/index.html

Change list:
* Add basic implementation for New Project/Open Project/Save/Save As... actions
* Remove Close Project because it is basically the same as New Project.

Add dialogs for open/save project

---

package.json

Reverts os-fpga/rapid_power_estimator#82

Revert "Update tool name in package.json"

---

backend/api/io.py
backend/api/utils.py
backend/restapi_server.py
backend/submodule/io.py
backend/submodule/peripherals.py
backend/submodule/rs_device.py
backend/submodule/rs_device_resources.py
backend/submodule/rs_message.py
src/utils/io.js

This PR contains the implementation of the IO dynamic power and resource utilization calculation.
Changes:
1. IO dynamic power computation
2. IO resource utilization calculation
3. The attributes API endpoint to return a list of attributes and the associated options used in the RPE

Implement IO dynamic power and resource utilization calculation

---

backend/api/utils.py
backend/submodule/dsp.py
backend/utilities/common_utils.py

This PR extended the built-in enum class to support text description requested by UI.

Add enum description text support

---

src/components/Tables/ACPUTable.js
src/components/Tables/BCPUTable.js
src/components/Tables/ConnectivityTable.js
src/components/Tables/DMATable.js
src/components/Tables/MemoryTable.js
src/components/Tables/TableCells.js

Change list:
* Fixed unit for bandwidth from W to MB/s for blocks:
* Memory
* ACPU
* BCPU
* Connectivity
* DMA

Fixed units for bandwidth

---

src/components/ModalWindows/ModalWindow.js
src/components/ModalWindows/PeripheralsModal.js
src/components/SOCSummaryComponent.js
src/components/Tables/PeripheralsTable.js
src/components/Tables/TableCells.js

Change list:
* Add new field for peripherals table, IO Used. 
* Fixed status icon for Memory component

Peripherals io usage

---

backend/submodule/peripherals.py
backend/submodule/rs_device_resources.py

This PR implemented OCM memory power calculation, total power consumption by subsystem and power usage in percentage.

Peripheral Power Calculation - Part 2

---

main.js

Change list:
* Add Close Project action

Add Close Project action

---

backend/api/project.py
backend/restapi_server.py
backend/submodule/rs_project.py

This is PR implement the backend APIs for RPE project file saving and loading features:-
1. Query & retrieve project attributes e.g. name, lang, notes, state etc.
2. Update project details e.g. name, lang, notes etc.
NOTE: This PR doesn't include API to save/load project in filesystem.

Project Save & Load Backend API - Part 1

---

.github/pull_request_template.md

> - [x] To address an existing issue. Updates the PR template.
> Minor fixes to template
>
> Accommodates new addtitions to PR from team. 
> 
> - [ ] Library: <Specify the library name>
> - [ ] Plug-in: <Specify the plugin name>
> - [ ] Engine
> - [X] Documentation
> - [ ] Require a change on Quality of Results (QoR)
> - [ ] Break back-compatibility. If so, please list …

Update pull_request_template.md based on team feedback

---

backend/api/errors.py
backend/api/project.py
backend/submodule/peripherals.py
backend/submodule/rs_device_resources.py
backend/submodule/rs_project.py

> - [x] To address an existing issue. If so, please provide a link to the issue: Project file APIs implementation part 2 for create new, open existing, save & save as use cases.
> - [ ] Breaking new feature. If so, please describe details in the description part. 
> This is the 2nd part of the project file API implementation
> The PR Implemented the backend RESTful APIs to create new, open/load, save and save as PRE project files. The current implementation only persists the project specific details and NO device inputs are saved in the file. Persisting device inputs will be included into following parts of …

Project api part 2

---

main.js
src/App.js
src/utils/serverAPI.js

Change list:
* Update New/Close action with API call. Now design name, language and notes cleared after New/Close pressed.

New action UI implementation

---

main.js
projectFile.js
src/App.js
src/utils/common.js
src/utils/serverAPI.js

Change list:
* Make Open/Save/Save as actions works with the backend
* Add standard shortcuts
* Rework Last Edit label. Now it is showing last save time. 
* Make Save button working (The one in the GUI)
* Improve save file dialog. Now file extension *.rpe will always be added to the file even if user remove it.
* Replace `formatString` with standard JS approach.

Add project Save/Open work with backend

---

main.js
src/App.js

Change list:
* Make Auto Save persistent between sessions.

Add autoSave field to a persistency storage

---

src/App.js

Change list:
* Remove handling `last edit` field from the Frontend
* Load `last edit` from the backend.

Load last edit field from the backend

---

src/App.js
src/components/DeviceList.js
src/tests/DeviceList.test.js

Change list:
* Update device selector when open project file.
Note. As for now device selector can't be changed to initial value.

Change device selector when open project file

---

src/GlobalStateProvider.js
src/components/ModalWindows/DMAModal.js
src/components/Tables/DMATable.js

Change list:
* DMA Source and Destination how gives a list from the backend
* Fixed issue if the Source and Destination list, when all items doubled.
* Fixed DMA errors/warnings in the Power Summary table.
* Add `NOC Power` column to DMA table.

DMA component, Frontend fixes

---

backend/api/clock.py
backend/api/errors.py
backend/api/project.py
backend/etc/device.xml
backend/submodule/bram.py
backend/submodule/clock.py
backend/submodule/dsp.py
backend/submodule/fabric_logic_element.py
backend/submodule/io.py
backend/submodule/peripherals.py
backend/submodule/rs_device.py
backend/submodule/rs_device_manager.py
backend/submodule/rs_device_resources.py
backend/submodule/rs_message.py
backend/submodule/rs_project.py

> Main change list:
> - Save and load inputs for clocking, dsp, bram, fabric le and io submodules (excludes peripheral inputs)
> - Clear user inputs for all devices when project closing and/or loading API are invoked.
> Additional changes:
> - Update device.xml
> - Remove hardcoded peripheral list & create device peripherals according to device.xml configs
> 
> - [x] Backend: <Specify backend components>
> - [ ] Library: <Specify the library …

Save, load and clear device inputs 

---

src/App.js
src/GlobalStateProvider.js
src/SOCTotalPowerProvider.js
src/components/FPGASummaryComponent.js

Cleanup UI after New/Close pressed.

Cleanup UI after New/Close pressed

---

backend/api/bram.py
backend/api/clock.py
backend/api/device.py
backend/api/dsp.py
backend/api/fabric_le.py
backend/api/io.py
backend/api/peripherals.py
backend/submodule/rs_project.py

> Change:
> - Set project modified flag to True when any device input update is performed.
> 
> - [x] Backend: Project API module

Set project modified flag when device inputs change

---

backend/api/peripherals.py
backend/submodule/rs_message.py
backend/submodule/rs_project.py

> Changes:
> - Save and load device peripherals to/from project file
> 
> - [x] Backend: RPE Project file Save/Soad modules

Save & load peripheral input of devices in project file

---

src/App.js
src/components/Tables/ACPUTable.js
src/components/Tables/BCPUTable.js
src/components/Tables/BramTable.js
src/components/Tables/ClockingTable.js
src/components/Tables/ConnectivityTable.js
src/components/Tables/DMATable.js
src/components/Tables/DspTable.js
src/components/Tables/FleTable.js
src/components/Tables/IOTable.js
src/components/Tables/MemoryTable.js
src/components/Tables/PeripheralsTable.js

Update all components tables after New/Close pressed.
Before:
After:

Clean component table when user choose New/Close action

---

backend/submodule/rs_message.py

> - [x] To address an existing issue. If so, please provide a link to the issue: <n/a>
> Change:
> - Fix unknown error when source & destination are same in DMA component
> 
> - [x] Backend: Error Message module

Fix unknown error when source & destination are same in DMA component

---

backend/api/device.py
backend/submodule/rs_device.py
backend/submodule/rs_project.py

> - [X] Breaking new feature. If so, please describe details in the description part.
> Change:
> - Save & load device power and thermal spec user inputs in project file
> 
> - [X] Backend: Project module

save & load device power & thermal spec inputs

---

src/App.js

Replace Invalid date with N/A

---

main.js
src/App.js
src/components/Tables/ACPUTable.js
src/components/Tables/BCPUTable.js
src/components/Tables/BramTable.js
src/components/Tables/ClockingTable.js
src/components/Tables/ConnectivityTable.js
src/components/Tables/DMATable.js
src/components/Tables/DspTable.js
src/components/Tables/FleTable.js
src/components/Tables/IOTable.js
src/components/Tables/MemoryTable.js
src/components/Tables/PeripheralsTable.js

Change List:
* Add modify data flag for all tables. In case anything was modified we show asterisk in the title. Also we check this flag before clear or open file.
* Change modification message
* Fixed issue when tables where not updated after open file.

Add modification flag indication

---

backend/api/project.py

> Change:
> - Serialize access to critical section using lock mechanism
>
> 
> - [x] Backend: Project API module

Serialize access to critical section using lock mechanism

---

src/App.js
src/GlobalStateProvider.js

Issues was fixed by https://github.com/os-fpga/rapid_power_estimator/pull/122
Clean up frontend code here.

Code cleanup for endpoints and attributes

---

src/components/PeripheralsComponent.js

Show only available peripherals.

Update peripherals component. Show only available peripherals

---

src/App.js
src/GlobalStateProvider.js
src/SOCTotalPowerProvider.js
src/components/ABCPUComponent.js
src/components/ConnectivityComponent.js
src/components/DMAComponent.js
src/components/DeviceList.js
src/components/MemoryComponent.js
src/components/PeripheralsComponent.js
src/components/SOCComponent.js
src/components/SOCSummaryComponent.js
src/components/Tables/ACPUTable.js
src/components/Tables/BCPUTable.js
src/components/Tables/BramTable.js
src/components/Tables/ClockingTable.js
src/components/Tables/ConnectivityTable.js
src/components/Tables/DMATable.js
src/components/Tables/DspTable.js
src/components/Tables/FleTable.js
src/components/Tables/IOTable.js
src/components/Tables/MemoryTable.js
src/components/Tables/PeripheralsTable.js
src/tests/DeviceList.test.js

Allow user select `Select device...` from the device list. This allow to reset this selector when New/Close was pressed.

Reset device selection after New/Close pressed

---

src/components/PeripheralsComponent.js

Cleanup code after https://github.com/os-fpga/rapid_power_estimator/pull/125

Fixed peripherals component

---

src/components/ABCPUComponent.js
src/components/ConnectivityComponent.js
src/components/DMAComponent.js

Fixed ACPU, BCPU, Connectivity, DMA after New/Close action.

Fixed New/Close acions

---

backend/api/io.py
backend/submodule/io.py
backend/submodule/rs_device_resources.py
backend/submodule/rs_message.py
backend/submodule/rs_project.py

> Change:
> - Save and load IO On-Die Termination (ODT) user input in RPE Project file
> 
> - [x] Backend: Project & IO Modules

save & load io odt inputs

---

backend/api/errors.py
backend/api/io.py
backend/submodule/io.py
backend/submodule/rs_device_resources.py
backend/submodule/rs_project.py

> Change:
> - Implement On-Die Termination (ODT) IO feature REST API
> 
> - [x] Backend: IO & RESTfull API modules

On-Die Termination (ODT) IO feature REST API

---

main.js
src/App.js

Show error message when open file failed.

Show error message when failed to open file

---

main.js
src/App.js
src/components/FpgaCell.js

Hide Sample project menu and Design parameters table.
Remove placeholders for power percentage of FPGA blocks

Hide Sample project menu and Design parameters table

---

src/components/ComponentsLib.js
src/components/Tables/ACPUTable.js
src/components/Tables/BCPUTable.js
src/components/Tables/ConnectivityTable.js
src/components/Tables/DMATable.js

Make sure all fields are disabled when no device selected or block is not available for the selected device.

Disable tables that can't be edited for current device

---

.github/workflows/rpe_test.yml
README.md
requirements.txt

1. Updated rpe_test.yml file with the steps needed to generate the code coverage statistics, 
2. Added a codecov_token to the main branch
3. Code coverage will now be visible on the main branch after the merge.
> 
> - [x] Continuous Integration (CI) scripts

Codecov for RPE

---

README.md

Fix the code coverage fetch URL in readmd.md

Update README.md to correct the codecov URL

---

src/preferences.js

> NA
>
> Fixed typo.
> 
> - [x] Backend: <Specify backend components>
> - [ ] Require a …

Fix device.xml typo in preferences.js

---

tests/api_tests/test_errors_api.py

PyTests for errors.py api are making sure that our custom exceptions are correct and that the error messages and status codes in our errors dictionary are accurate. This will involve writing Pytest unit tests to:
1. Verify Exception Handling: Ensure each custom exception can be raised and caught properly.
2. Validate Error Dictionary: Check that each key in the errors dictionary corresponds to the correct error message and status code.
> 
> - …

Pytests for Error Handling

---

src/tests/DMAComponent.test.js
tests/api_tests/test_fabric_le_api.py

PyTests for the Fabric_LesApi, Fabric_LeApi, and Fabric_LeConsumptionApi methods. The tests cover the following functionalities:
GET method for fetching logic elements.
POST method for adding a new logic element.
PATCH method for updating an existing logic element.
DELETE method for removing a logic element.
GET method for checking resource consumption.
> 
> - [x] Backend: <Specify backend components>
> - [ ] Library: <Specify the library …

PyTests for Fabric Logic Element API

---

src/tests/TitleComponent.test.js
src/tests/TypicalWorstComponent.test.js

React tests for the TypicalWorstComponent.js using Jest. The tests verify the rendering of typical and worst-case power and temperature values and check for proper display of default values when no data is available. It also make sure that the thunderbolt icon appears in both columns.
1. Added mock implementation for the useSocTotalPower hook.
2. Tested correct display of power and temperature for typical and worst cases.
3. Tested rendering of default values when no data is …

React/Jest Tests for TypicalWorstComponent.js

---

src/tests/FPGASummaryComponent.test.js
src/tests/MemoryComponent.test.js
src/tests/Notes.test.js
src/tests/SOCComponent.test.js

Adds unit tests to verify the rendering and functionality of the FPGA summary component and makes sure that the component handles power summary data properly.
Tests the initial rendering of the MemoryComponent with mock peripheral data and checks the display of memory and power consumption values.
Adds tests for the Notes modal component and verifies form submission, input change handling, and modal close behavior (including clicking the close icon and pressing the Escape key).
Adds unit tests to verify the rendering of child components …

FPGA Summary, Memory, Notes and SOC Components in React using Jest

---

tests/api_tests/test_dsp_api.py

Pytests that validate the responses of DSP API endpoints. 
Covers the following scenarios:
1. Retrieving a list of all DSP modules.
2. Fetching a specific DSP module by row number.
3. Getting the power consumption of a DSP module.
4. These tests used a mock implementation of RsDeviceManager, MockDevice, and MockDspModule to simulate API responses.
Implemented Pytests for:
GET /devices/<device_id>/dsp endpoint
GET /devices/<device_id>/dsp/<rownum> endpoint
GET /devices/<device_id>/dsp/consumption endpoint
Each Pytest checks the following:
1. …

Pytests for DSP API Endpoints

---

backend/etc/devices/mpw1/power_data.json
backend/etc/devices/mpw1/uart.json
backend/submodule/rs_device_resources.py
backend/submodule/rs_power_config.py
tests/test_rs_device_resources.py

> Change
> - Migrate hardcoded uart peripheral power calculation coefficient to JSON power config file
> 

Move Uart peripheral power data into JSON power config file

---

tests/api_tests/test_peripherals_api.py

> - [x] To address an existing issue.
Pytests for PeripheralSchema and its peripheral types, including SPI, JTAG, and I2C. Also making sure that the schema correctly processes both valid and invalid inputs. 
> #### What is currently done? (Provide issue link if applicable) - 
Pytests for Perpherals API including- 
1. test_get_peripheral_schema_spi(): Making sure correct schema selection for SPI peripheral.
2. test_get_peripheral_schema_jtag(): Validates schema selection for JTAG peripheral.
3. test_get_peripheral_schema_default(): Tests the fallback schema selection.
4. test_get_type_valid(): Validates correct peripheral type …

Pytests for peripheral API Schema and Validation Handling

---

tests/test_clock_api.py

Added new test cases to improve coverage and the correct functionality of Clock and Clock_SubModule. Following test Cases are being added:
1. test_add_clock_success: Verifies successful clock addition with valid data.
2. test_add_clock_duplicate_raises_exception: Makes sure adding duplicate clocks raises an exception.
3. test_add_clock_max_limit_reached: Confirms adding beyond the limit triggers an exception.
4. test_remove_clock_success: Tests successful clock removal.
5. test_remove_clock_not_found: Validates exception raised for invalid …

Updating pytests for test_clock.py to improve code coverage 

---

tests/test_device_resource_under_devices_file.py

Pytests to verify the correct initialization and default behavior of the ResourceAttributes, InternalAttributes, Device, and DeviceList classes. (This is for device_resource.py file under ‘devices’ in backend folder.) The tests ensure that attributes in these classes are properly set and initialized. Tests should include checks for default values, custom initialization, and object attributes.
Acceptance Criteria: Unit tests cover the following classes:
1. ResourceAttributes
2. InternalAttributes
3. Device
4. DeviceList
The following tests …

Pytests for device_resource.py file under ‘devices’ in backend folder

---

backend/etc/devices/mpw1/acpu.json
backend/etc/devices/mpw1/power_data.json
backend/submodule/rs_device_resources.py
tests/test_rs_device_resources.py

> Change:
> - Migrate hardcoded ACPU power calculation coefficient to JSON power config file
> 

Move ACPU power data into JSON power config file

---

src/tests/PeripheralComponents.test.js

1. PeripheralsComponent using React Testing Library and Jest. It covers scenarios rendering with initial data, fetching peripherals data from the server, and updating the component when a new device prop is passed.  
2. The test suite validates that empty blocks are correctly rendered when peripherals data is missing.
> 
> - [x] Frontend: <Specify frontend components> PeripheralComponent.test.js
> - [ ] Library: <Specify the library name, e.g. …

React/Jest tests for PeripheralsComponent.js

---

backend/etc/devices/mpw1/gpio.json
backend/etc/devices/mpw1/power_data.json
backend/submodule/rs_device_resources.py
backend/submodule/rs_power_config.py
tests/test_rs_device_resources.py

> Change:
> - Migrate hardcoded GPIO power calculation coefficient to external JSON power config file
> 

Move GPIO power data into JSON power config file

---

src/tests/ConnectivityComponent.test.js

Jest tests for the ConnectivityComponent.js to check the following:
1. The component renders correctly with the default state.
2. The component disables when no FPGA complex peripherals are available.
3. The component updates properly when the device prop changes.
> 
> - [x] Frontend: <Specify frontend components>ConnectivityComponent.test.js
> - [ ] Plug-in: <Specify the plugin name, …

React/Jest tests for ConnectivityComponents.js

---

backend/etc/devices/mpw1/ddr.json
backend/etc/devices/mpw1/power_data.json
backend/submodule/peripherals.py
backend/submodule/rs_device_resources.py
backend/submodule/rs_power_config.py
tests/test_rs_device_resources.py

> Change:
> - Migrate hardcoded DDR power calculation coefficient to external JSON power config file
> 

Move DDR power data into JSON power config file

---

backend/etc/devices/mpw1/power_data.json
backend/etc/devices/mpw1/sram.json
backend/submodule/rs_device_resources.py
backend/submodule/rs_power_config.py
tests/test_rs_device_resources.py

> Change:
> - Migrate hardcoded SRAM power calculation coefficient to external JSON power config file
> 

Move SRAM power data into JSON power config file

---

jest.config.js
src/tests/ComponentsLib.test.js

Jest tests for the components in ComponentsLib.js using Jest. The following components are covered:
1. State: Tested for error, warning, and normal states.
2. ComponentLabel: Verified the correct rendering of labels.
3. AddButton: Tested for button functionality and disabled state.
4. Checkbox: Checked toggling behavior and the checkHandler.
5. PercentSelector: Ensured correct percentage selection.
6. Dropdown: Tested dropdown value changes.
> 
> - [x] Frontend: <Specify frontend …

React/Jest Tests for ComponentsLib.js

---

backend/etc/devices/mpw1/power_data.json
backend/etc/devices/mpw1/regulator.json
backend/submodule/rs_device_resources.py
backend/submodule/rs_power_config.py
tests/test_rs_device_resources.py

> Change:
> - Migrate hardcoded regulator values to external JSON power config file
> 

Move regulator values into JSON power config file

---

backend/etc/devices/mpw1/power_data.json
backend/etc/devices/mpw1/pwm.json
backend/submodule/peripherals.py
backend/submodule/rs_device_resources.py
backend/submodule/rs_power_config.py
tests/test_rs_device_resources.py

> Change:
> - Migrate hardcoded PWM peripheral power calculation coefficient to external JSON power config file
> 

Move PWM peripheral power data into JSON power config file

---

src/tests/ABCPUComponent.test.js

1. Jest test for the ABCPUComponent to check that it renders correctly with the provided props. 
2. The test verifies the display of the title, power value, and percentage when the component is enabled.
> 
> - [x] Frontend: <Specify frontend components> ABCPUComponent.test.js
> - [ ] Regression …

React/Jest tests for ABCPUComponent Rendering

---

src/tests/SOCSummaryComponent.test.js

> ### Describe technical details - 
Jest tests check that the component renders correctly, passes the right data to the PowerSummaryTable, and handles the device prop properly
> 
> - [x] Frontend: <Specify frontend components>SOCSummaryComponent.test.js
> ### Impact of …

React/jest tests for SOCSummaryComponent.js

---

src/tests/FpgaComponent.test.js

Jest tests to: 
1. Verify that the FpgaComponent renders the FPGA title without crashing.
2. Confirm that the total power displayed matches the mock value of 2000.
> 
> 
> 
>
> 
> 
> 
> 
> 
> - [x] Frontend: <Specify frontend components> FpgaComponent.test.js
> - [ ] Plug-in: …

React/jest tests for FPGAComponent.js

---

src/tests/SelectionProvider.test.js

Jest tests for SelectionProvider.js - 
1. Verifies that SelectionProvider starts with a default value (Clocking).
2. Tests that items (Memory, CPU, Peripherals) are correctly selected when clicked.
3. Confirms that the clear selection button works as expected.
4. Checks that switching between items (e.g. Memory and CPU) and selecting arbitrary items (Peripherals) functions properly.
> 
> - [x] Frontend: <Specify frontend components> SelectionProvider.test.js
> - [ ] Backend: <Specify …

React/Jest tests for SelectionProvider.js

---

src/tests/SOCTotalPowerProvider.test.js

Jest tests for SOCTotalPowerProvider.js:
1. Rendering provider with default context values.
2. Correct update of the dynamic power when updateTotalPower is called.
3. Correct update of the static power when updateTotalPower is called.
4. Proper update of the total percentage upon power update.
> 
> - [x] Frontend: <Specify frontend components> SOCTotalPowerProvider.test.js
> - [ ] …

React/Jest tests for SOCTotalPowerProvider.js

---

src/tests/index.test.js
src/tests/preferences.test.js

1. Jest tests to check that the App component renders properly within its providers without crashing. 
2. It also makes sure that the GlobalStateProvider gets the server.GET function as a prop. 
3. The tests confirm that the App component works well with GlobalStateProvider, ClockSelectionProvider, SocTotalPowerProvider, and SelectionProvider. 
4. The server.GET function and App component are mocked for testing purposes. Finally, the tests make sure all components load without any issues.
> …

React/Jest tests for index.js

---

src/tests/ClockSelectionProvider.test.js

Jest tests for ClockSelectionProvider component to check that it behaves as expected. These tests validate that clocks are properly set, cleared, and the default clock is updated correctly based on the provided context
1. Initial rendering provides default context values (empty clocks and default clock).
2. Clocks can be set and the first clock in the list becomes the default clock.
3. Clocks can be cleared, resetting the default clock to an empty state.
4. Multiple clock sets maintain the correct clock values.
5. The defaultClock function …

React/Jest tests for ClockSelectionProvider.js

---

src/tests/GlobalStateProvider.test.js

1. Added Jest unit tests for GlobalStateProvider.js to verify the default state values (clockingState, peripherals, acpuNames) in GlobalStateProvider.
2. Added a test to mock peripheral data fetching and ensure the peripheral count updates correctly when the "Update Global State" button is clicked.
> 
> - [x] Frontend: <Specify frontend components>GlobalStateProvider.test.js
> - [ ] …

React/Jest tests for GlobalStateProvider.js

---

src/tests/App.test.js

Jest tests for App.js, in the process of writing tests, starting with a test that checks if the App component renders correctly with the default content, including the "Top level name" placeholder, "Auto save", and "Auto Mode" text.
> 
> 
> 
>
> 
> 
> 
> 
> 
> - [x] Frontend: <Specify frontend components> App.test.js
> - [ ] Library: …

React/Jest tests for App.js

---

src/tests/main.test.js

> ### Describe the technical details - Jest tests for main.js, tests for:
1. Verifying that a BrowserWindow is created when the app is ready.
2. Checking that the Flask server starts when the app is ready.
3. Checking if the app quits when all windows are closed on non-macOS platforms.
4. Testing that project data is sent correctly when the projectData event is received.
5. Validating that configuration settings are sent when the config event is received.
6. Handling the app relaunch event.
> 
> - [x] Frontend: <Specify frontend …

React/Jest tests for main.js

---

src/tests/Tables_tests/BCPUTable.test.js

> ### Describe the technical details -  
1. Checks that the BCPUTable component renders correctly.
2. Verifies that the server.GET function is called when the component mounts.
> 
> - [x] Frontend: <Specify frontend components>BCPUTable.test.js
> ### Impact of the pull …

React/Jest tests for BCPUTable.js

---

src/tests/Tables_tests/DesignParametersTable.test.js

> ### Describe the technical details 
Tests that cover -
1. Rendering all required elements such as labels and buttons (LUTs, FFs, BRAMs, DSP, RISC-V ACPU checkbox, DDR dropdown, OCM, Calculate button).
2. Handling state changes for the RISC-V ACPU checkbox, including checking and unchecking.
3. Handling input change for the RISC-V ACPU frequency.
4. Handling dropdown selection change for DDR.
5. Simulating the click event on the Calculate button.
> 
> - [x] Frontend: <Specify frontend components>DesignParametersTable.test.js
> - …

React/Jest tests for DesignParametersTable.js

---

src/tests/Tables_tests/ConnectivityTable.test.js

For ConnectivityTable.js, tests for -
1. Rendering the component and verifying that necessary elements like 'Connectivity' and 'Connectivity power' are displayed.
2. Handling server API responses and displaying rows based on the available endpoints.
3. Checking if the "Add" button is initially disabled as expected.
> 
> - [x] Frontend: <Specify frontend components>ConnectivityTable.test.js
> - [ ] Library: <Specify the library name, e.g. npm …

React/Jest tests for ConnectivityTable.js

---

src/tests/Tables_tests/PowerTable.test.js

Jest tests for PowerTable.js - 
1. Rendering the component with the correct title and total.
2. Correctly displaying the subheader when provided.
3. Handling cases where the total value is null.
4. Checking if the fixed function is called correctly for resources and totals.
5. Verifying percentage rendering based on resources.
> 
> - [x] Frontend: <Specify frontend components>PowerTable.test.js
> - [ ] Library: <Specify the library name, e.g. …

React/Jest tests for PowerTable.js

---

src/tests/Tables_tests/IOPowerTable.test.js

Jest tests for IOPowerTable.js:
1. Checks if the title and total power are displayed correctly.
2. Makes sure the resource table renders the correct data, including banks used, IO used, voltage, and percentage.
3. Verifies that cells with errors are styled properly.
4. Confirms that multiple rows of resource usage are rendered.
5. Checks the correct formatting of the total power value and verifies the correct rendering of voltage and availability.
> 
> - [x] Frontend: <Specify frontend …

React/Jest test for IOPowerTable.js

---

src/tests/Modal_tests/ABCPUModal.test.js

Jest tests for ABCPUModal.js, covering scenarios -
1. Modal renders with the correct title (Test Modal).
2. closeModal is called when the modal's close button is clicked.
3. onSubmit is called with the correct data when the form is submitted.
4. Verified the presence of the Cancel button.
5. Confirmed the correct number of options in the endpoint select field.
6. Ensured the OK button is rendered and functional.
> 
> 
> 
>
> 
> 
> 
> …

Adding a folder for ModalWindows test files and react/jest tests for ABCPUmodal.js

---

src/tests/Modal_tests/BramModal.test.js

1. Modal renders with the correct title.
2. closeModal function is called when the close button is clicked.
3. onSubmit function is called with correct data when the form is submitted.
4. Cancel button is correctly rendered.
> 
> - [x] Frontend: <Specify frontend components>BramModal.test.js
> - [ ] …

React/Jest tests for BramModal.js

---

src/tests/Modal_tests/ConnectivityModal.test.js

1. Modal renders with the correct title ("Connectivity Modal").
2. closeModal function is triggered when the close button is clicked.
3. onSubmit function is called with the correct default data when the form is submitted.
4. Cancel button is correctly rendered within the modal.
5. Clock select dropdown renders with the correct options (Clock1 and Clock2).
> 
> - [x] Frontend: <Specify frontend components>ConnectivityModal.test.js
> - [ ] …

React/Jest tests for ConnectivityModal.js

---

src/tests/Modal_tests/ClockingModal.test.js

1. Verified the correct title is rendered.
2. Made sure closeModal is called when the close button is clicked.
3. Checked that onSubmit is called with the correct data when the form is submitted.
4. Made sure that Cancel button is rendered.
> 
> - [x] Frontend: <Specify frontend components>ClockingModal.test.js
> - [ ] …

React/Jest tests for ClockingModal.js

---

src/tests/Modal_tests/DMAModal.test.js

1. Verifies that the modal displays the correct title ("DMA Modal").
2. Checks that the closeModal function is called when the close button is clicked.
3. Checks that the onSubmit function is triggered with the correct data when the form is submitted.
4. Confirms that the "Cancel" button renders on the modal.
5. Validates that the default value for the "Channel Name" input field is displayed correctly.
> 
> - [x] Frontend: <Specify frontend components>DMAModal.test.js
> - [ ] Backend: …

React/Jest tests for DMAModal.js

---

src/tests/Modal_tests/PeripheralModal.test.js

1. Verified that the modal renders correctly with the correct title, based on the provided defaultValue.
2. Tested the closeModal functionality by ensuring the modal closes when the "Close" button is clicked.
3. Tested the onSubmit functionality by ensuring the form submission handler is triggered when the "Submit" button is clicked.
> 
> - [x] Frontend: <Specify frontend components>PeripheralModal.test.js
> - [ ] Library: <Specify the library …

React/Jest tests for PeripheralModal.js

---

.github/workflows/rpe_test.yml

> - [ x] To address an existing issue. If so, please provide a link to the issue: <issue id>
Fix the capture of coverage report to upload to codecov
> 
> 
> 
>
> 
> 
> 
> 
> 
> - [ x] Continuous Integration (CI) …

Fix the capture of coverage report to upload to codecov

---

src/tests/Tables_tests/MemoryTable.test.js

1. Added tests to verify that the MemoryTable header is rendered correctly.
2. Added tests to validate that the memory power total is displayed accurately.
> 
> - [x] Frontend: <Specify frontend components>MemoryTable.test.js
> ### …

React/Jest tests for MemoryTable.js

---

README.md

Added 'docs: passing" badge to readme (redirects to readthedocs for RPE link) alongside build and publish RPE and codecov badge. 
> 
> - [x] Documentation: updated README
> …

Docs: passing badge to README

---

main.js

> ### Describe the technical details 
As discussed, disabling Config menu.
> 
> - [x] Frontend: <Specify frontend components> main.js
> - [ ] Require a change on Quality of Results (QoR)
> - [ ] Break backward-compatibility. If so, please …

Disabling Config menu

---

src/tests/Tables_tests/PeripheralsTable.test.js

Test checks for the presence of the expected table column headers - Peripherals, Action, Usage, Performance, IO used, Block Power.
> 
> - [x] Frontend: <Specify frontend components>PeripheralsTable.test.js
> ### Impact of the pull …

React/Jest tests for PeripheralsTable.js

---

.github/workflows/rpe_test.yml

> - [x] To address an existing issue. If so, please provide a link to the issue: RPE-157
> 
> 
> 
>
> 
> 
> 
> 
> 
> - [x] Continuous Integration (CI) scripts
The macos 12 image is …

Update rpe_test.yml to use macos latest

---

.github/workflows/rpe_test.yml

> - [x ] To address an existing issue. If so, please provide a link to the issue: <issue id>
Upload artefact version update to v4
> 
> 
> 
>
> 
> 
> 
> 
> 
> - [ x] Continuous Integration (CI) scripts
> ### Impact …

Upload artefact version update to v4

---

src/components/ModalWindows/ClockingModal.js
src/components/Tables/ClockingTable.js

@MustafaAbdaal, as discussed - 
> 
> 
> 
>
> 
> 
> 
> 
> 
> - [x] Frontend: <Specify frontend components>ClockingModal.js. ClockingTable.js
> - [ ] Continuous …

Changing clocking frequency label to Frequency (Hz)
