src/components/ModalWindows/ModalWindow.js, src/components/Tables/ACPUTable.js, src/components/style/ACPUTable.css, src/components/style/PowerTable.css
Updates:
1. Add ACPU table add/modify/delete functionality
2. Update ACPU table components view
3. Fixed issue with Toggle Rate fields in different tables when user try to modify it.
Open issue:
* Need to work on rows order in ACPU table. As for now, it is always ordered by port number.
* Reflect endpoints power on the main block (green one)
=> Add ACPU table add/remove/modify functionality

main.js, package.json, preload.js, src/App.js, src/SelectionProvider.js, src/components/ConnectivityComponent.js, src/components/DMAComponent.js, src/components/DeviceList.js, src/components/FpgaCell.js, src/components/MemoryComponent.js, src/components/PeripheralsComponent.js, src/components/SOCComponent.js, src/index.js, src/preferences.js, src/style.css, src/utils/common.js
Updates:
* Preferences menu allow change port and device.xml path.
* Restart application when settings changed.
* Enable persistence user data (electron-store). Now we can persist any data between sessions.
* Organize IPC communication between main process and renderer process.
* preload.js script now is available. 
* Indicate selected element
* Make device selection component selectable. 
With warning:
Selection:
=> Add preferences menu, add components selection

.github/workflows/rpe_test.yml, .gitignore, package.json
Added preload.js in package
pyinstaller command is now part of the dist command
Upload artifacts on every push to the main branch
Upload to package to release area on push of git tag
=> Update Rapid Power Estimator to upload package tar file on every push

src/components/ComponentsLib.js, src/components/DMAComponent.js, src/components/ModalWindows/ModalWindow.js, src/components/Tables/BramTable.js, src/components/Tables/ClockingTable.js, src/components/Tables/DMATable.js, src/components/Tables/DspTable.js, src/components/Tables/FleTable.js, src/components/Tables/IOTable.js
Updates:
* Fixed UI fatal error after modifying any table.
* Add checkboxes for most of the tables, which allow user to enable/disable any table rows.
* Change DMA table, now whole table is available for modification, Add button removed.
* DMA channel names synchronized for both view (data table and main table)
Note. Enable/Disable does not implemented for ACPU/BCPU and Connectivity tables since the API does not allow this.
=> Fixed UI fatal after modify any data

cleanup.js, main.js, package.json
Use `tree-kill` package for killing processes on Windows. For linux this doesn't work since command `ps -o pid --no-headers --ppid PID` that is run under the hood returns nothing.
=> Fixed window issue with backend processes

main.js, src/App.js, src/components/ModalWindows/ABCPUModal.js, src/components/ModalWindows/BramModal.js, src/components/ModalWindows/ClockingModal.js, src/components/ModalWindows/ConnectivityModal.js, src/components/ModalWindows/DMAModal.js, src/components/ModalWindows/DspModal.js, src/components/ModalWindows/FleModal.js, src/components/ModalWindows/IOModal.js, src/components/ModalWindows/ModalWindow.js, src/components/Tables/ACPUTable.js, src/components/Tables/BCPUTable.js, src/components/Tables/BramTable.js, src/components/Tables/ClockingTable.js, src/components/Tables/ConnectivityTable.js, src/components/Tables/DMATable.js, src/components/Tables/DesignParametesTable.js, src/components/Tables/DspTable.js, src/components/Tables/FleTable.js, src/components/Tables/IOTable.js, src/components/Tables/MemoryTable.js, src/components/Tables/PeripheralsTable.js, src/components/style/ACPUTable.css, src/components/style/ComponentTable.css, src/components/style/ComponentsLib.css, src/style.css
Updates:
* Top tables layout changed: all three tables width have 54/22/22 % of the width (the number 54 looks better to me then 50% or 60%). Top row of the tables does not change it's height during resize, but the width only.
* Update main layout: now scrolls appears mostly for bottom tables (both vertical and horizontal)
* Improve modal windows (this window allow modify table data): enable scroll bars, use modal component from ant library.
* Cleanup css for tables borders
* improve tables layout: remove main-block element.
Note1. There are still few TODOs for main scroll bars
Note2. Currently tables scroll bars hide Power table. But probably Power table should be visible all the time. 
Note3. Main scroll bars still can appears after make window very small. This will be fixed later.
=> Layout update

src/App.js, src/components/ConnectivityComponent.js, src/components/MemoryComponent.js, src/components/SOCComponent.js, src/components/Tables/MemoryTable.js, src/style.css
Change list:
* Make Memory component optional that depends on data received from peripherals API. 
* Fixed FPGA component layout.
Note. Still need update summary table for memory.
=> Make memory component optional

src/App.js, src/components/ABCPUComponent.js, src/components/CPUComponent.js, src/components/ConnectivityComponent.js, src/components/DMAComponent.js, src/components/MemoryComponent.js, src/components/PeripheralsComponent.js, src/components/SOCComponent.js, src/components/Tables/ConnectivityTable.js, src/components/Tables/PeripheralsTable.js, src/components/style/FpgaComponent.css, src/components/style/Peripherals.css
Change list:
* Prepare SOC blocks for possible cases then no such peripheral in the device.
* Show grayed component
* Such block can't be selected.
Items in progress:
* Power table need to update according to the components existence.
* When user click to disabled block, need to prevent corresponding table opening
=> Add possibility for some blocks display as not available

src/components/Tables/MemoryTable.js
Fixed memory component crash. 
Crash occurs when select memory component first and then select device.
=> Fixed memory component crash

src/App.js, src/GlobalStateProvider.js
Fetch attributes fires before the right port was set. 
The fix is make sure fetching attributes fires after the port setup.
=> Fixed issue when fetch attributes failed for non-default port

src/components/FPGASummaryComponent.js, src/components/FpgaComponent.js
> ### Describe the technical details - Fixing DSP power issue - The DSP power value was not correctly displaying in the FPGA Summary View. Although the DSP power data is being fetched correctly and is visible in the lower section of the interface, it was not rendered in the middle blocks of the FPGA summary area. But fixed it.
> 
> - [x] Frontend: <Specify frontend components>
> - [ ] Plug-in: <Specify the plugin name, …
=> Fixing DSP Power Issue

backend/etc/devices/mpw1/power_data.json, backend/etc/devices/mpw1/qspi.json, backend/submodule/rs_device_resources.py, backend/submodule/rs_power_config.py, tests/test_rs_device_resources.py
> Change
> - Migrate hardcoded q/spi peripheral power calculation coefficient to JSON power config file
> 
=> Move Q/SPI peripheral power data into JSON power config file

backend/etc/devices/mpw1/jtag.json, backend/etc/devices/mpw1/power_data.json, backend/submodule/rs_device_resources.py, backend/submodule/rs_power_config.py, tests/test_rs_device_resources.py
> Change:
> - Migrate hardcoded JTAG peripheral power calculation coefficient to external JSON power config file
> 
> - [x] Backend: Power Config Module
=> Move JTAG peripheral power data into JSON power config file

backend/etc/devices/mpw1/i2c.json, backend/etc/devices/mpw1/power_data.json, backend/submodule/rs_device_resources.py, backend/submodule/rs_power_config.py, tests/test_rs_device_resources.py
> Change:
> - Migrate hardcoded I2C peripheral power calculation coefficient to external JSON power config file
> 
> - [x] Backend: Power Config Module
=> Move I2C peripheral power data into JSON power config file

backend/etc/devices/mpw1/gige.json, backend/etc/devices/mpw1/power_data.json, backend/submodule/rs_device_resources.py, backend/submodule/rs_power_config.py, tests/test_rs_device_resources.py
> Change:
> - Migrate hardcoded Gigabit Ethernet peripheral power calculation coefficient to external JSON power config file
> 
> - [x] Backend: Power Config Module
=> Move Gigabit Ethernet peripheral power data into JSON power config file

backend/etc/devices/mpw1/power_data.json, backend/etc/devices/mpw1/usb2.json, backend/submodule/rs_device_resources.py, backend/submodule/rs_power_config.py, tests/test_rs_device_resources.py
> Change:
> - Migrate hardcoded U2B2 peripheral power calculation coefficient to external JSON power config file
> 
=> Move USB2 peripheral power data into JSON power config file

backend/submodule/peripherals.py
> Change:
> - Issue: The Pwm0 class in peripherals module uses wrong child classes (properties_ & output_) from Gpio0 classes. 
> - Fix: Use these child classes defined within Pwm0 class itself.
> 
> - [x] Backend: PWM Peripheral Module
> - [ ] Continuous Integration (CI) …
=> Fix PWM compute object use wrong prop & output child classes

src/components/ModalWindows/PeripheralsModal.js
Fixing issue where pressing the Enter key in the "IO Used" field of the Peripherals modal causes the screen to turn white and reset to the initial stage.
> 
> - [x] Frontend: <Specify frontend components>PeripheralModal.js
> ### …
=> Fixing the RPE crash error when editing GPIO Peripheral in popup dialog

src/tests/Tables_tests/ACPUTable.test.js
1. Created a new folder named tables_tests inside the tests directory to hold test files for the components table.
2. Added an initial Jest test file for APCUTable.js to ensure the basic functionality of the component is covered.
> 
> - [x] Frontend: <Specify frontend components>Tables_Tests > APCUTable.test.js
> - [ ] …
=> Adding folder for Tables tests and adding a sample jest test for APCUTable.js

src/tests/Modal_tests/MemoryModal.test.js
1. Verifies that the modal window displays with the correct title and fields.
2. Tests that the "Data Rate" and "Width" fields have default values of 3200 and 64.
3. Makes sure the closeModal function runs when the close button is clicked.
4. Verifies the onSubmit function is called when the form is submitted.
5. Confirms the modal window appears in the DOM.
> 
> - [x] Frontend: <Specify frontend components>MemoryModal.test.js
> - [ ] Library: …
=> React/Jest tests for MemoryModal.js

src/tests/Modal_tests/ModalWindow.test.js
Tests for ModalWindow.js that checks
1. Rendering the modal with the correct title.
2. Verifying that all input fields are rendered with the correct default values.
3. Triggering the closeModal function when the close button is clicked.
4. Triggering the onSubmit function with the correct data when the form is submitted.
5. Making sure that input fields (name, age, percentage, and clock) update correctly when their values are changed.
> 
> - [x] Frontend: <Specify frontend …
=> React/Jest tests for ModalWindow.js

main.js, src/App.js, src/tests/App.test.js
1. Auto Save button is now set to "off" by default and cannot be changed (frozen in the off position).
2. Auto Mode button is disabled, so it can't be clicked or changed.
> 
> - [x] Frontend: <Specify frontend components> main.js and src/App.js
> - [ ] Continuous Integration …
=> Disabling the Auto Save and Auto Mode button on the UI

src/tests/Modal_tests/IOModal.test.js
1. Verifies that the modal title is displayed correctly.
2. Makes sure the closeModal function is called when the cancel button is clicked.
3. Tests that the onSubmit function is called with the correct data when the form is submitted.
4. Checks that form fields (e.g., RTL Port Name, bus width, clock selection) are updated when the user changes their values.
> 
> - [x] Frontend: <Specify frontend components>IOModal.test.js
> - [ ] Library: …
=> React/Jest tests for IOModal.js

src/tests/Modal_tests/FleModal.test.js
1. Rendering the modal with the correct title and default values for all input fields.
2. Handling user interactions such as changing input fields, selecting options, and clicking buttons.
2. Checking that the closeModal and onSubmit callback functions are invoked with the correct data when the respective buttons are clicked.
> 
> - [x] Frontend: <Specify frontend components>FleModal.test.js
> - [ ] Library: <Specify the library name, e.g. npm …
=> React/Jest tests for FleModal.js

backend/restapi_server.py, backend/submodule/peripherals.py, backend/submodule/rs_logger.py
> 1. Implement simple backend logger to capture application for troubleshoot and debugger use.
> 2. Support file rotating capability with configurable max size and backup count options.
> 3. The log file will be saved in User home directory
> 4. The log file name will be "rpe.log"
> 5. Log file behavior: Resume if the rpe.log exists.
> 
> - [x] Backend: RsLogger module
> - [ ] …
=> Simple logger for backend log messages

backend/submodule/rs_device.py, backend/submodule/rs_device_resources.py, backend/submodule/rs_power_config.py, tests/test_rs_power_config.py
> Changes:
> 1. Allow devices without power_data config in device.xml to be loaded in RPE
> 2. Do not raise exception if a device has not power_data config.
> 3. Do not exit backend process when a device has not power_data config
> 4. Allow RPE to run even there are devices without power_data config.
> 
> - [x] Backend: DeviceManager, PowerCfg modules
> - [ ] Plug-in: <Specify the …
=> Allow loading device without power data config

src/components/Tables/ACPUTable.js, src/components/style/ACPUTable.css
> ### Describe the technical details: 
1. A toggle switch has been added to enable or disable ACPU parameters in the UI.
2. The switch is implemented using the Switch component and controls the ACPU settings based on the user input.
3. When toggled, it will either activate or deactivate the ACPU power and functionality.
Updated UI: 
> 
> - [x] Frontend: <Specify frontend components> ACPUTable.css, ACPUTable.js
> - [ ] …
=> Enabling ACPU UI to provide a way for user to enable/disable ACPU

src/tests/Tables_tests/BramTable.test.js
1. Renders the BRAM power table and verifies headers like "Used," "Total," "BRAM Type," "Action," and "Name/Hierarchy" are displayed.
2. Checks if the checkbox for enabling/disabling BRAM rows is rendered and toggles correctly, triggering a PATCH request.
3. Verifies that clicking the "Add" button opens a modal for adding/editing a BRAM row.
4. Confirms that submitting the form in the modal sends a POST request with the new BRAM data.
5. Checks that the modal closes after submission or when clicking the "Close" button.
> ### Which part of …
=> React/Jest tests for BramTable.js

src/tests/Tables_tests/PowerSummaryTable.test.js
1. The table title and total power values are correctly displayed.
2. Each row renders the correct power and percentage values.
3. Warning and error tooltips are displayed when applicable.
4. No tooltips are shown for rows without messages.
> 
> - [x] Frontend: <Specify frontend components>PowerSummaryTable.test.js
> - [ …
=> React/Jest tests for PowerSummaryTable.js

projectFile.js
> ### Describe the technical details 
When a project is saved, the application will now:
1. Prompt the user to select or name the project folder.
2. Create a directory based on the project name.
3. Save the project file inside the directory with the .rpe extension.
4. Update the window title to reflect the project file name.
> 
> - [x] Frontend: <Specify frontend components>projectfile.js
> - [ ] Plug-in: <Specify the …
=> Implement Project Save Feature with Directory Creation Based on User Input

.readthedocs.yml, docs/Makefile, docs/make.bat, docs/source/api_inference.rst, docs/source/conf.py, docs/source/index.rst, docs/source/installation.rst, docs/source/usage.rst, requirements.txt
An initial setup for integrating readthedocs into RPE repository. 
It includes the configuration files to generate and host project documentation using Sphinx and readthedocs.
1. Added a .readthedocs.yml configuration file to define the readthedocs build process.
2. Created and structured the docs/ directory for Sphinx-based documentation.
3. Added an initial index.rst file with sections for Introduction, History, GUI Design and Technology Choices, and Contents. (Mustafa and team can pick it up from here)
4. Set up conf.py for Sphinx to use …
=> readthedocs for RPE

src/tests/Tables_tests/DspTable.test.js
> ### Describe the technical details 
1. Verifies the DspTable component renders correctly with the DSP title and table headers.
2. Checks that the DSP data is displayed as expected, including block name, mode, input width, clock frequency, and power.
> 
> - [x] Frontend: <Specify frontend components>DspTable.test.js
> - [ ] Regression …
=> React/Jest tests for DspTable.js

requirements.txt
Adding comments next to each package in the requirements.txt file. 
The comments give a short explanation of what each package does. 
This makes it easier for developers to understand why each package is included.
> 
> - [x] …
=> Add comments to requirements.txt to explain each package

src/tests/SOCComponent.test.js
Verified the total_power and total_percentage values are displayed correctly in the TitleComponent.
> 
> - [x] Frontend: <Specify frontend components> SOCComponent.test.js
> - [ ] Require a change …
=> Updating SOCComponent.test.js

.github/workflows/rpe_test.yml, .gitignore, jest.config.js, package.json, playwright.config.js, tests/e2e/acpu.test.js, tests/e2e/bcpu.test.js, tests/e2e/clocking.test.js, tests/e2e/dsp.test.js, tests/e2e/fle.test.js
1. Playwright Setup:
Added playwright.config.js for Playwright testing setup. Created a new folder playwright_e2e/ with test files for ACPU, BCPU, DSP, FLE, and clocking
2. Updated jest.config.js to exclude some folders and improve test coverage.
3. Adjusted the setup for better Playwright integration.
4. Updated .gitignore to ignore Playwright test results, reports, and cache files.
5. As discussed, creating a test folder named 'e2e' under 'tests' folder as our desired location for Playwright test suites.
> ### Which part of the code base …
=> Setting up Playwright testing env and config.js, adding e2e folder under tests

src/tests/Tables_tests/PowerSummaryTable.test.js
Renders the PowerSummaryTable component with an empty data array, total set to 0, and percent set to 0.
Asserts that the title ("Power Summary") is displayed.
> 
> - [x] Frontend: <Specify frontend components> PowerSummaryTable.test.js
> - [ ] Continuous Integration (CI) …
=> Adding unit tests for PowerSummaryTable.js

backend/restapi_server.py, cleanup.js, main.js, tests/e2e/restart.test.js
1. Adding signal handlers for shutting down the process to the backend (restapi_server.py).
2. Added restart.test.js e2e test.
> 
> 
> 
>
> 
> 
> 
> 
> 
> - [x] Backend: <Specify backend components>restapi_server.py
> - [ ] Plug-in: <Specify the plugin name, e.g. Webpack, …
=> Added Signal Handlers to the backend for shutting down the process and adding restart.test.js

.github/workflows/rpe_test.yml, main.js, package.json, webpack.config.js
> - [x ] To address an existing issue. If so, please provide a link to the issue: <issue id>
Webpack is optimising the Typescript in production mode due to this the frontend cannot fetch data from backend. So for now disabled the webpack production mode and package the assets in development mode.  
> 
> 
> 
>
> 
> 
> 
> 
> 
> - [ x] Frontend: <Specify frontend components>
> - [ ] Library: <Specify the library name, e.g. npm …
=> Disable webpack production mode in packaging to fix issue in linux

backend/submodule/peripherals.py, src/components/ModalWindows/BramModal.js, src/components/ModalWindows/DspModal.js, src/components/Tables/BramTable.js, src/components/Tables/DspTable.js
As per the discussion, 
1. Updating for DSP Modal - Changing 'XX' to 'Number of Multipliers'.
2. 1. Updating for BRAM Modal - Changing 'Used' to 'BRAMs Used'.
3. 1. Updating for BCPU Modal - Removing Frequencies. Eg: 'BOOT CLK(40 Mhz) is now 'BOOT CLK'.
> 
> 
> 
>
> 
> 
> 
> 
> 
> - [ ] …
=> Updating labels for BRAM, DSP and BCPU modals
